// Техническая подготовка QA
export const techTestQA = [
  {
    question: 'How many testing principles are there?',
    questionId: 1,
    answers: ['5', '6', '7', '8', '9', "I don't know"],
    rightAnswer: '7',
  },
  {
    question: 'Verification is – ',
    questionId: 2,
    answers: [
      'In fact, it answers the question of whether the software is created and tested correctly and whether all the requirements are taken into account',
      'During the verification process, we make sure that all the created application functionality works correctly and logically, right',
      'The verification structure includes such components as verification of validated requirements, technical documentation and correct execution of program code at any stage of software development and testing',
      'Options 2 and 3 are correct',
      'All options are correct',
      'All options are incorrect',
    ],
    rightAnswer: 'All options are correct',
  },
  {
    question: 'Validation is – ',
    questionId: 3,
    answers: [
      'Answers the question whether the product is being created correctly in terms of customer expectations',
      'During the validation process, we make sure that the product fully complies with the behavior that is expected of it and that the client knows about the presence of such functionality',
      'Validation, in its essence, largely includes an overall assessment of the software and can be based solely on subjective opinion regarding the correct operation of the application or its components',
      'Options 1 and 3 are correct',
      'All options are correct',
      'All options are incorrect',
    ],
    rightAnswer: 'All options are correct',
  },
  {
    question: 'Which of the following is a MINUS in the Waterfall method?',
    questionId: 4,
    answers: [
      'High transparency of development and project phases',
      'Stability of requirements',
      'Facilitates the work of drawing up a project plan and assembling a project team',
      'All requirements must be known at the beginning of the project life cycle',
      'Clear consistency',
      'All options are correct',
      'All options are incorrect',
    ],
    rightAnswer: 'All requirements must be known at the beginning of the project life cycle',
  },
  {
    question:
      'THIS software development methodology is mainly aimed at reducing the work being done at the moment. In this methodology: there are no time limits for either tasks or sprints; there are more and fewer tasks; There is no direct need to set deadlines for completing tasks, but you still need to measure them for a general presentation. What methodology are we talking about?',
    questionId: 5,
    answers: [
      'Waterfall',
      'Scrum',
      'Agile',
      'Kanban',
      'This definition applies to all methodologies',
      'There is not a right option',
    ],
    rightAnswer: 'Kanban',
  },
  {
    question: 'What does XP stands for in testing',
    questionId: 6,
    answers: [
      'eXPerience',
      'eXtreme Programming',
      'eXperience Points',
      'XP Injection',
      'All options are correct',
      'All options are incorrect',
    ],
    rightAnswer: 'eXtreme Programming',
  },
  {
    question: "Agile's main ideas",
    questionId: 7,
    answers: [
      'People and interactions are more important than processes and tools',
      'A working product is more important than comprehensive documentation',
      'Cooperation with the customer is more important than agreeing on the terms of the contract',
      'Being ready for change is more important than following the original plan',
      'All options are correct',
      'All options are incorrect',
    ],
    rightAnswer: 'All options are correct',
  },
  {
    question:
      'What methodology are these 4 stages about: Inception, Elaboration, Construction, Transition',
    questionId: 8,
    answers: ['RUP', 'Kanban', 'Scrum', 'Agile', 'Waterfall', 'All options are incorrect'],
    rightAnswer: 'RUP',
  },
  {
    question: 'The correct sequence of Scrum elements',
    questionId: 9,
    answers: [
      'Sprint Planning and Sprint Backlog Creation - Working on the sprint. Scrum meetings - Product testing and demonstration - Retrospective. Planning the next sprint',
      'Creating a product backlog - Working on a sprint. Scrum meetings - Product testing and demonstration - Retrospective. Planning the next sprint',
      'Product Backlog Creation - Sprint Planning and Sprint Backlog Creation - Product Testing and Demo - Retrospective. Planning the next sprint',
      'Creating a Product Backlog - Planning a Sprint and creating a Sprint Backlog - Working on a Sprint. Scrum meetings - Retrospective. Planning the next sprint',
      'Creating a Product Backlog - Planning a Sprint and creating a Sprint Backlog - Working on a Sprint. Scrum meetings - Product testing and demonstration',
      'All options are incorrect',
    ],
    rightAnswer: 'All options are incorrect',
  },
  {
    question: 'What skills are most often required from a project manager?',
    questionId: 10,
    answers: [
      'Collection and systematization of project requirements',
      'Work execution plan, KPI, mindmaps',
      'Search for performers, freelancers, drawing up a portrait of the desired employee for HR',
      'Setting tasks and monitoring deadlines',
      'All options are correct',
      'All options are incorrect',
    ],
    rightAnswer: 'All options are correct',
  },
  {
    question: 'What are the tasks of the Product Owner?',
    questionId: 11,
    answers: [
      'Setting tasks and monitoring deadlines',
      'Control of budget spending',
      'Maintenance of project documentation (technical specifications, contracts, acts, invoices, estimates, reports)',
      'And once again - BUDGETS and TERMS - this is what is most important in his work',
      'All options are correct',
      'All options are incorrect',
    ],
    rightAnswer: 'All options are incorrect',
  },
  {
    question: 'Product Owner controls',
    questionId: 12,
    answers: [
      'Who uses the product and which features are important to users, and which are secondary',
      'How users solve problems and problems, and who they are',
      'How you can attract more users; how to keep current ones and how to bring them to payment',
      'Why users abandon the product (it may be in an inconvenient interface, technical bugs, lack of necessary functions or cost)',
      'All options are correct',
      'All options are incorrect',
    ],
    rightAnswer: 'All options are correct',
  },
  {
    question: 'What is dynamic testing?',
    questionId: 13,
    answers: [
      'This is testing by only executing code with different input values and confirming the results',
      'This is testing by executing only the program with different input values and confirming the results',
      'This is testing by executing a code or program with different input values and confirming the results',
      'This is testing by executing code',
      'This is testing with different inputs and validation of the results.',
      "I don't know",
    ],
    rightAnswer:
      'This is testing by executing a code or program with different input values and confirming the results',
  },
  {
    question: 'What is formal testing?',
    questionId: 14,
    answers: [
      'Verification of software, according to the test plan, test procedures and relevant documentation, taking into account the wishes of the client',
      'Validation of software, according to the test plan, test procedures and relevant documentation, taking into account the wishes of the client',
      'Verification of software, according to test procedures and relevant documentation, without taking into account the wishes of the client',
      "I don't know",
    ],
    rightAnswer:
      'Verification of software, according to the test plan, test procedures and relevant documentation, taking into account the wishes of the client',
  },
  {
    question:
      'The usability of the interface is usually determined through a number of qualitative indicators',
    questionId: 15,
    answers: [
      'Learnability, efficiency, errors, satisfaction',
      'Learnability, memorability, errors, satisfaction',
      'Efficiency, memorability, errors, satisfaction',
      'Learnability, efficiency, memorability, errors',
      'Learnability, efficiency, memorability, errors, satisfaction',
      "I don't know",
    ],
    rightAnswer: 'Learnability, efficiency, memorability, errors, satisfaction',
  },
  {
    question: 'What is Showstopper defect',
    questionId: 16,
    answers: [
      'A defect that forces you to rollback the last release',
      'A defect that allows you to make an immediate release without testing',
      'A defect that forces you to stop the testing progress',
      'A defect, which is that there is no defect. But there must be',
      'All options are correct',
      'All options are incorrect',
    ],
    rightAnswer: 'A defect that forces you to stop the testing progress',
  },
  {
    question: 'STLC is – ',
    questionId: 17,
    answers: [
      'The stage at which the testing strategy is determined',
      'Software testing life cycle',
      'Final stage of software testing',
      'This abbreviation has nothing to do with testing',
      'All options are correct',
      'All options are incorrect',
    ],
    rightAnswer: 'Software testing life cycle',
  },
  {
    question: 'Which of the following is superfluous',
    questionId: 18,
    answers: [
      'Test plan',
      'Bug report',
      'Backlog',
      'Check list',
      'Cheat list',
      'Set of test cases and kits',
    ],
    rightAnswer: 'Backlog',
  },
  {
    question: 'The test plan answers questions like this',
    questionId: 19,
    answers: [
      "What's need to be tested",
      "What's going to be tested",
      'How and when is it going to be tested',
      'Test start and end criteria',
      'All options are correct',
      'All options are incorrect',
    ],
    rightAnswer: 'All options are correct',
  },
  {
    question: 'What is superfluous in the criteria for launching testing?',
    questionId: 20,
    answers: [
      'SRS - software',
      'FRS',
      'Use case',
      'Test plan',
      'All options are correct',
      'All options are incorrect',
    ],
    rightAnswer: 'All options are incorrect',
  },
  {
    question: 'What is superfluous in the criteria for completing testing',
    questionId: 21,
    answers: [
      'Testing report',
      'Metrics',
      'Test Analysis Report',
      'Test case',
      'All options are correct',
      'All options are incorrect',
    ],
    rightAnswer: 'Test case',
  },
  {
    question:
      'This is a comprehensive user testing of concurrent access to an application to verify the impact on a code, module or database. Mainly detects deadlocks in code.',
    questionId: 22,
    answers: [
      'Currency testing',
      'Testing the web application',
      'Functional testing',
      'Interface testing',
      'Gamma testing',
      "I don't know",
    ],
    rightAnswer: 'Currency testing',
  },
  {
    question:
      'This testing is done on the website to check loading, performance, security, functionality, interface, compatibility and other usability related issues',
    questionId: 23,
    answers: [
      'Currency testing',
      'Testing the web application',
      'Functional testing',
      'Interface testing',
      'Gamma testing',
      "I don't know",
    ],
    rightAnswer: 'Testing the web application',
  },
  {
    question:
      'Item testing (or side testing) allows you to test individual work of source code units',
    questionId: 24,
    answers: [
      'Currency testing',
      'Testing the web application',
      'Functional testing',
      'Interface testing',
      'Gamma testing',
      "I don't know",
    ],
    rightAnswer: 'Functional testing',
  },
  {
    question:
      'Interface testing checks the interaction of individual modules. Most often used to test the user interface of GUI applications',
    questionId: 25,
    answers: [
      'Currency testing',
      'Testing the web application',
      'Functional testing',
      'Interface testing',
      'Gamma testing',
      "I don't know",
    ],
    rightAnswer: 'Interface testing',
  },
  {
    question:
      'This testing is carried out when the software is already ready for release, it is checked for compliance with the requirements.',
    questionId: 26,
    answers: [
      'Currency testing',
      'Testing the web application',
      'Functional testing',
      'Interface testing',
      'Gamma testing',
      "I don't know",
    ],
    rightAnswer: 'Gamma testing',
  },
];

//  Теория тестирования
export const teoryTest = [
  {
    question: "What does 'CI' stands for in QA?",
    questionId: 1,
    answers: ['Connection interface', 'Nothing', 'Continuous Integration', 'Centiliter'],
    rightAnswer: 'Continuous Integration',
  },
  {
    question: 'Testing stages. Choose the right sequence',
    questionId: 2,
    answers: [
      'Requirements Management - Product Analysis - Developing a Test Strategy and Planning Quality Control Procedures - Generating Test Documentation - Prototype Testing - Basic Testing - Stabilization - Operation',
      'Product analysis - Working with requirements -. Developing a test strategy and planning quality control procedures - Creating test documentation - Prototype testing - Basic testing - Stabilization - Operation',
      'Requirements Management - Product Analysis - Developing a Test Strategy and Planning Quality Control Procedures - Prototype Testing - Generating Test Documentation - Basic Testing - Stabilization - Operation',
      'Requirements Management - Product Analysis - Developing a Test Strategy and Planning Quality Control Procedures - Generating Test Documentation - Prototype Testing - Stabilization - Basic Testing - Operation',
      'Requirements Management - Product Analysis - Developing a Test Strategy and Planning Quality Control Procedures - Prototype Testing - Generating Test Documentation - Basic Testing - Stabilization - Operation',
    ],
    rightAnswer:
      'Product analysis - Working with requirements -. Developing a test strategy and planning quality control procedures - Creating test documentation - Prototype testing - Basic testing - Stabilization - Operation',
  },
  {
    question: 'What are the main benefits of automated testing?',
    questionId: 3,
    answers: [
      'Fast execution',
      'Reduced software maintenance costs',
      'Saving testers time',
      'Possibility of execution outside working hours',
      'All options are correct',
      'All options are incorrect',
    ],
    rightAnswer: 'All options are correct',
  },
  {
    question: 'What are the main types of locators in Selenium?',
    questionId: 4,
    answers: [
      'ID, ClassName',
      'Name, TagName',
      'LinkText, PartialLinkText',
      'Xpath, CSS Selector, DOM',
      'All options are correct',
      'All options are incorrect',
    ],
    rightAnswer: 'All options are correct',
  },
  {
    question: 'Provide correct example of Absolute XPath',
    questionId: 5,
    answers: [
      'html/body/div/[3]/div/div/[1]/div/div/div[1]/div/input',
      'html/body/div(3)/div/div(1)/div/div/div)1)/div/input',
      'html\bodydiv[3]divdiv[1]divdivdiv[1]divinput/',
      'html//body/div[3]/div/div[1]/div/div/div[1]/div/input',
      'html/body/div[3]/div/div[1]/div/div/div[1]/div/input',
    ],
    rightAnswer: 'html/body/div[3]/div/div[1]/div/div/div[1]/div/input',
  },
  {
    question:
      'Most often, viewing elements in the Google Chrome browser on windows is launched by the button',
    questionId: 6,
    answers: ['F5', 'F7', 'F2', 'F9', 'F12'],
    rightAnswer: 'F12',
  },
  {
    question:
      'Most often, viewing items in the Google Chrome browser on Mac is launched by this key combination',
    questionId: 7,
    answers: ['Cmd+Opt+O', 'Cmd+Opt+R', 'Cmd+Opt+J', 'Cmd+Opt+N', 'Cmd+Opt+W'],
    rightAnswer: 'Cmd+Opt+J',
  },
  {
    question: 'navigate().back(). This navigation command in Selenium:',
    questionId: 8,
    answers: [
      'Returns the user to the previous page from the browser history',
      'Allows the user to navigate to the next page according to the browser history',
      'Used to refresh the browser page',
      'Allows the user to open a new window in the browser and follow the specified URL',
      'There is no such command',
    ],
    rightAnswer: 'Returns the user to the previous page from the browser history',
  },
  {
    question: 'navigate().forward(). This navigation command in Selenium:',
    questionId: 9,
    answers: [
      'Returns the user to the previous page from the browser history',
      'Allows the user to navigate to the next page according to the browser history',
      'Used to refresh the browser page',
      'Allows the user to open a new window in the browser and follow the specified URL',
      'There is no such command',
    ],
    rightAnswer: 'Allows the user to navigate to the next page according to the browser history',
  },
  {
    question: 'navigate().refresh(). This navigation command in Selenium:',
    questionId: 10,
    answers: [
      'Returns the user to the previous page from the browser history',
      'Allows the user to navigate to the next page according to the browser history',
      'Used to refresh the browser page',
      'Allows the user to open a new window in the browser and follow the specified URL',
      'There is no such command',
    ],
    rightAnswer: 'Used to refresh the browser page',
  },
  {
    question: 'navigate().to(). This navigation command in Selenium:',
    questionId: 11,
    answers: [
      'Returns the user to the previous page from the browser history',
      'Allows the user to navigate to the next page according to the browser history',
      'Used to refresh the browser page',
      'Allows the user to open a new window in the browser and follow the specified URL',
      'There is no such command',
    ],
    rightAnswer: 'Allows the user to open a new window in the browser and follow the specified URL',
  },
  {
    question: 'Which of the following is a bug report attribute',
    questionId: 12,
    answers: [
      'Summary',
      'Attachments',
      'Status',
      'Severity',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'Continuous Integration',
  },
  {
    question:
      'Testing that deals with the security of the application and aims to prevent problems that could affect the integrity and stability of the application:',
    questionId: 13,
    answers: [
      'Penetration testing',
      'Fuzzy testing',
      'Ramp testing',
      'Vulnerability testing',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'Vulnerability testing',
  },
  {
    question:
      '______ is an existing defect that has not yet caused the failure because the conditions required to trigger the defect are not met',
    questionId: 14,
    answers: [
      'Hidden defect and disguised defect',
      'Hidden defect',
      'Disguised defect',
      'Defect',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'Hidden defect',
  },
  {
    question: 'Testing outside of normal performance is',
    questionId: 15,
    answers: [
      'Stress testing',
      'Performance testing',
      'Functional testing',
      'Centiliter',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'Stress testing',
  },
  {
    question:
      "The tester runs a test to evaluate whether it meets the user's request to fill in a specific field using a drop-down list containing a list of values. The tester performs",
    questionId: 16,
    answers: [
      'Stress testing',
      'Regression testing',
      'White box testing',
      'Black box testing',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'Black box testing',
  },
  {
    question: 'Checking the onBlur field is done',
    questionId: 17,
    answers: [
      'When we hover over the field',
      'When we start entering data',
      'When we press the submit button',
      'After entering data',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'When we press the submit button',
  },
  {
    question: "What's wrong appealing to Smoke and sanity tests?",
    questionId: 18,
    answers: [
      'If both are running, do sanity tests first and then smoke testing',
      'Sanity Testing is also called Tester Acceptance Testing',
      'Smoke and sanity tests can be performed using an automation tool',
      'Smoke testing performed for a specific build is also called build verification test',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'If both are running, do sanity tests first and then smoke testing',
  },
  {
    question: 'The Paradox Pesticide Testing Principle suggests that',
    questionId: 19,
    answers: [
      'Finding and eliminating defects does not help if the system is unstable',
      'Testing is done differently in a different context',
      'Test cases should be reviewed and revised regularly',
      'Clustering modules that contain most of the defects',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'Test cases should be reviewed and revised regularly',
  },
  {
    question:
      "What kind of testing allows a tester to evaluate the software's behavior when exceptions are thrown?",
    questionId: 20,
    answers: [
      'Injection test malfunction',
      'Passive testing',
      'Fuzzy testing',
      'Centiliter',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'Injection test malfunction',
  },
  {
    question: 'White box testing does not concern',
    questionId: 21,
    answers: [
      'Decision-making',
      'Causes and effects of coverage',
      'Multiple coverage conditions',
      'Coverage Statement',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'Causes and effects of coverage',
  },
  {
    question: 'Which of the following is not part of specification-based testing?',
    questionId: 22,
    answers: [
      'State transition',
      'Decision table',
      'Boundary value analysis',
      'Data stream',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'Data stream',
  },
  {
    question: 'What is the order of priority testing?',
    questionId: 23,
    answers: [
      'System >> Reception >> Integration',
      'System >> Integration >> Acceptance Testing',
      'Module >> Integration >> System testing',
      'Module >> System >> Acceptance test',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'Module >> Integration >> System testing',
  },
  {
    question: 'Application does not allow the configuration expected by the client, is an example',
    questionId: 24,
    answers: [
      'High severity and high priority',
      'High severity and low priority',
      'Low Severity and Low Priority',
      'Low Severity and High Priority',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'High severity and low priority',
  },
  {
    question:
      'What is the balance of effort required to fix a defect in the requirements phase, design phase, coding phase, and implementation phase?',
    questionId: 25,
    answers: [
      '1: 8: 12: 100',
      '1: 4: 7: 10',
      '1: 10: 100: 1000',
      '1: 6: 10: 1000',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: '1: 6: 10: 1000',
  },
  {
    question: 'What is the percentage of software development costs?',
    questionId: 26,
    answers: [
      '10-20',
      '40-50',
      '5-10',
      '70-80',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: '40-50',
  },
  {
    question: 'Which of the following is not an iterative model?',
    questionId: 27,
    answers: [
      'Incremental',
      'Spiral Model',
      'V model',
      'RAD',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'V model',
  },
  {
    question: 'Verification and validation uses',
    questionId: 28,
    answers: [
      'External resources only',
      'Only internal resources',
      'External and Internal resources, respectively',
      'Internal and external resources, respectively',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'Internal and external resources, respectively',
  },
  {
    question:
      "Upon opening a link to a website, the user receives the message 'This section of our website is under construction.'' Then what is this mistake?",
    questionId: 29,
    answers: [
      'URL error',
      'Functional error',
      'Structural error',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'All options are incorrent',
  },
  {
    question:
      'Is a testing technique that involves testing with different ranges of valid and invalid inputs a specific module or component functionality?',
    questionId: 30,
    answers: [
      'Baseline testing',
      'Gorilla Testing',
      'Monkey testing',
      'Agile testing',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'Gorilla Testing',
  },
  {
    question: 'Focus testing falls under _______',
    questionId: 31,
    answers: [
      'Usability testing',
      'Component testing',
      'Acceptance testing',
      'Performance testing',
      'All options are correct',
      'All options are incorrent',
    ],
    rightAnswer: 'Usability testing',
  },
];
